Repository micronaut-projects/micronaut-redis, pull requests merged in 2021-03, with the labels that each got.

#164 build: bump up micronaut-gradle-plugins to 3.0.3
  build.gradle
Labels: type: dependency-upgrade

#166 build: gradle from gradle-6.8.2 to gradle-6.8.3
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#168 Fix leaking connections in health indicator
  redis-lettuce/build.gradle
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/health/RedisHealthIndicator.java
Labels: type: bug

#170 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#171 [redis] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#177 Use AbstractRedisConfiguration name field for name qualifier
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/AbstractRedisConfiguration.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisServersConfiguration.java
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/RedisClientFactorySpec.groovy
Labels: type: bug

#178 use Micronaut @Nullable annotation
  gradle.properties
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/AbstractRedisClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClusterClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisClientFactory.java
Labels: type: improvement

#174 refactor: extract private methods
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/health/RedisHealthIndicator.java
Labels: type: improvement

#180 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade
