Repository micronaut-projects/micronaut-redis, pull requests merged in 2022-03, with the labels that each got.

#258 build: Lettuce from 6.1.1 to 6.1.6
  gradle.properties
Labels: type: dependency-upgrade

#254 ci: sonarqube
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/sonarqube.yml
  MAINTAINING.md
  SECURITY.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#264 ci: checkout v3
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: relates-to: build

#265 build: update build plugin to 5.2.3
  settings.gradle
Labels: relates-to: build

#267 ci: checkstyle SupressionFilter
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#268 Add BOM to redis module
  redis-bom/build.gradle
  settings.gradle
Labels: relates-to: build

#271 Next minor
  gradle.properties
  redis-lettuce/build.gradle
Labels: relates-to: build

#270 Use version catalogs for dependencies
  gradle.properties
  gradle/libs.versions.toml
  redis-bom/build.gradle
  redis-lettuce/build.gradle
Labels: relates-to: build

#272 build: gradle 7.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#275 Properly clean-up the application context
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/session/RedisSessionSpec.groovy
Labels: relates-to: redis

#282 [redis] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build
