Repository micronaut-projects/micronaut-redis, pull requests merged in 2023-05, with the labels that each got.

#372 [redis] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/graalvm.yml
  buildSrc/src/main/groovy/io.micronaut.build.internal.redis-native-tests.gradle
  test-suite-graal/build.gradle
Labels: relates-to: build

#374 Micronaut Framework 4.0.0-M4
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.redis-base.gradle
  gradle.properties
  gradle/libs.versions.toml
  redis-lettuce/build.gradle
  settings.gradle
  test-suite-graal/build.gradle
Labels: type: dependency-upgrade

#376 [redis] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#311 Use ExecutorService in RedisHealthIndicator
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/health/RedisHealthIndicator.java
Labels: type: improvement

#383 [redis] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
