Repository micronaut-projects/micronaut-redis, pull requests merged in 2024-07, with the labels that each got.

#540 [redis] Update common files for branch 6.5.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#544 MasterReplica and ReadFrom Support
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/AbstractRedisConfiguration.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClusterClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/NamedRedisClientFactory.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisConnectionUtil.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisSetting.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/RedisAsyncConnectionPoolFactory.java
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/DefaultRedisClusterClientFactorySpec.groovy
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/RedisReplicaClientFactorySpec.groovy
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/RedisReplicaSpec.groovy
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/cache/RedisClusterCacheSpec.groovy
  redis-lettuce/src/test/java/io/micronaut/redis/test/RedisReplicaContainerUtils.java
  src/main/docs/guide/config.adoc
Labels: type: enhancement

#545 Update invalidateAll implementation to use SCAN
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/AbstractRedisCache.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/AbstractRedisCacheConfiguration.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/RedisCache.java
  redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/RedisConnectionPoolCache.java
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/cache/RedisCacheSpec.groovy
  redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/cache/RedisJsonDeserializerCacheSpec.groovy
  redis-lettuce/src/test/java/io/micronaut/redis/test/RedisClusterContainerUtils.java
  redis-lettuce/src/test/java/io/micronaut/redis/test/RedisContainerUtils.java
  redis-lettuce/src/test/java/io/micronaut/redis/test/RedisReplicaContainerUtils.java
Labels: type: improvement

#551 [redis] Update common files for branch 6.5.x
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
